wc -l chr1_eur_case.hg19_multianno.txt
wc -l chr2_eur_case.hg19_multianno.txt
wc -l chr3_eur_case.hg19_multianno.txt
wc -l chr4_eur_case.hg19_multianno.txt
wc -l chr5_eur_case.hg19_multianno.txt
wc -l chr6_eur_case.hg19_multianno.txt
wc -l chr7_eur_case.hg19_multianno.txt
wc -l chr8_eur_case.hg19_multianno.txt
wc -l chr9_eur_case.hg19_multianno.txt
wc -l chr10_eur_case.hg19_multianno.txt
wc -l chr11_eur_case.hg19_multianno.txt
wc -l chr12_eur_case.hg19_multianno.txt
wc -l chr13_eur_case.hg19_multianno.txt
wc -l chr14_eur_case.hg19_multianno.txt
wc -l chr15_eur_case.hg19_multianno.txt
wc -l chr16_eur_case.hg19_multianno.txt
wc -l chr17_eur_case.hg19_multianno.txt
wc -l chr18_eur_case.hg19_multianno.txt
wc -l chr19_eur_case.hg19_multianno.txt
wc -l chr20_eur_case.hg19_multianno.txt
wc -l chr21_eur_case.hg19_multianno.txt
wc -l chr22_eur_case.hg19_multianno.txt
