python find_alt_allele.py chr3_eur_case.hg19_multianno.vcf 3 > chr03_3alt.txt
python find_alt_allele.py chr4_eur_case.hg19_multianno.vcf 3 > chr04_3alt.txt
python find_alt_allele.py chr5_eur_case.hg19_multianno.vcf 3 > chr05_3alt.txt
python find_alt_allele.py chr6_eur_case.hg19_multianno.vcf 3 > chr06_3alt.txt
python find_alt_allele.py chr7_eur_case.hg19_multianno.vcf 3 > chr07_3alt.txt
python find_alt_allele.py chr8_eur_case.hg19_multianno.vcf 3 > chr08_3alt.txt
python find_alt_allele.py chr9_eur_case.hg19_multianno.vcf 3 > chr09_3alt.txt
python find_alt_allele.py chr10_eur_case.hg19_multianno.vcf 3 > chr10_3alt.txt
python find_alt_allele.py chr11_eur_case.hg19_multianno.vcf 3 > chr11_3alt.txt
python find_alt_allele.py chr12_eur_case.hg19_multianno.vcf 3 > chr12_3alt.txt
python find_alt_allele.py chr13_eur_case.hg19_multianno.vcf 3 > chr13_3alt.txt
python find_alt_allele.py chr14_eur_case.hg19_multianno.vcf 3 > chr14_3alt.txt
python find_alt_allele.py chr15_eur_case.hg19_multianno.vcf 3 > chr15_3alt.txt
python find_alt_allele.py chr16_eur_case.hg19_multianno.vcf 3 > chr16_3alt.txt
python find_alt_allele.py chr17_eur_case.hg19_multianno.vcf 3 > chr17_3alt.txt
python find_alt_allele.py chr18_eur_case.hg19_multianno.vcf 3 > chr18_3alt.txt
python find_alt_allele.py chr19_eur_case.hg19_multianno.vcf 3 > chr19_3alt.txt
python find_alt_allele.py chr20_eur_case.hg19_multianno.vcf 3 > chr20_3alt.txt
python find_alt_allele.py chr21_eur_case.hg19_multianno.vcf 3 > chr21_3alt.txt
python find_alt_allele.py chr22_eur_case.hg19_multianno.vcf 3 > chr22_3alt.txt
